services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app

  cypress:
    image: cypress/included:13.14.2
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - vue-app
    entrypoint: ["npx", "cypress", "run"]
